import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CircleCheck, CircleHelp, LockKeyhole, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { Eyebrow, PageFrame } from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

type AuditForm = { name: string; email: string; phone: string; website: string; instagram: string; niche: string; offer: string; price: string; monthlyLeads: string; monthlyInquiries: string; bookedCalls: string; leadSource: string; currentSystem: string; challenge: string; marketingConsent: boolean; smsConsent: boolean; whatsappConsent: boolean };
type Category = { label: string; score: number; explanation: string; opportunity: string };
const initialForm: AuditForm = { name: "", email: "", phone: "", website: "", instagram: "", niche: "", offer: "", price: "", monthlyLeads: "", monthlyInquiries: "", bookedCalls: "", leadSource: "", currentSystem: "", challenge: "", marketingConsent: false, smsConsent: false, whatsappConsent: false };
const steps = ["Basics", "Offer", "Volume", "Source", "Current system", "Challenge"];

function scoreAudit(form: AuditForm): Category[] {
  const leads = Number(form.monthlyLeads.replace(/\D/g, "")) || 0;
  const inquiries = Number(form.monthlyInquiries.replace(/\D/g, "")) || 0;
  const booked = Number(form.bookedCalls.replace(/\D/g, "")) || 0;
  const bookingRate = leads > 0 ? booked / leads : 0;
  const traffic = form.leadSource ? (["referrals", "content", "youtube"].includes(form.leadSource) ? 72 : 58) : 28;
  const capture = form.website && form.offer ? 67 : form.website || form.offer ? 52 : 32;
  const nurturing = form.challenge === "poor-follow-up" || form.challenge === "leads-no-response" ? 28 : form.currentSystem === "dm" ? 35 : 48;
  const qualification = form.currentSystem === "application" ? 72 : form.currentSystem === "booking-page" ? 64 : form.currentSystem ? 52 : 31;
  const booking = bookingRate >= .2 ? 78 : bookingRate >= .1 ? 63 : booked ? 49 : 34;
  const followUp = form.challenge === "poor-follow-up" || form.challenge === "no-shows" ? 26 : form.challenge ? 46 : 39;
  const conversion = inquiries > 0 && booked > 0 ? Math.min(82, Math.round((booked / inquiries) * 100) + 45) : form.offer && form.niche ? 54 : 34;
  return [
    { label: "Traffic", score: traffic, explanation: traffic >= 60 ? "You have an identifiable path bringing attention toward your offer." : "Your primary lead source is a useful area to make more intentional.", opportunity: "Clarify which source brings the best-fit conversations, not just the most activity." },
    { label: "Lead Capture", score: capture, explanation: capture >= 60 ? "Your offer and online presence give you a starting point for capturing interest." : "There may be room to make the first step easier to understand and take.", opportunity: "Give interested prospects one clear next step instead of asking them to figure it out." },
    { label: "Nurturing", score: nurturing, explanation: nurturing >= 50 ? "Some follow-through signals are present, but consistency can still compound." : "The handoff after initial interest looks like a meaningful opportunity.", opportunity: "Build a short, useful follow-up path for people who are not ready today." },
    { label: "Qualification", score: qualification, explanation: qualification >= 60 ? "You have some structure for recognizing fit before a conversation." : "Qualification is a useful place to add clarity before a call.", opportunity: "Ask the right questions early so the strategy call starts with context." },
    { label: "Booking", score: booking, explanation: booking >= 60 ? "Your current booked-call pattern suggests there is a path worth strengthening." : "Booking is a useful place to reduce friction and add context.", opportunity: "Connect qualification and scheduling so the call feels like the natural next step." },
    { label: "Follow-Up", score: followUp, explanation: followUp >= 50 ? "You have a foundation to build on around timing and reminders." : "Post-inquiry or post-booking follow-up is likely an important leak.", opportunity: "Create clear next steps for no-shows, undecided prospects, and people who need more time." },
    { label: "Conversion", score: conversion, explanation: conversion >= 60 ? "Your offer and current activity create a foundation for better conversion decisions." : "There is an opportunity to make the path from interest to decision more deliberate.", opportunity: "Align message, proof, qualification, and call structure around one clear decision." },
  ];
}

export default function Audit() {
  const [form, setForm] = useState<AuditForm>(initialForm); const [step, setStep] = useState(0); const [result, setResult] = useState<Category[] | null>(null); const [submitError, setSubmitError] = useState("");
  const submitAudit = trpc.audit.submit.useMutation(); const categories = useMemo(() => result ?? scoreAudit(form), [form, result]); const overall = Math.round(categories.reduce((sum, category) => sum + category.score, 0) / categories.length); const update = (key: keyof AuditForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const canContinue = step === 0 ? Boolean(form.name && form.email && form.phone) : step === 1 ? Boolean(form.niche && form.offer && form.price) : step === 2 ? Boolean(form.monthlyLeads && form.monthlyInquiries && form.bookedCalls) : step === 3 ? Boolean(form.leadSource) : step === 4 ? Boolean(form.currentSystem) : Boolean(form.challenge && form.marketingConsent);
  async function finish(event?: FormEvent) { event?.preventDefault(); const scored = scoreAudit(form); setResult(scored); setSubmitError(""); try { await submitAudit.mutateAsync({ ...form, overallScore: Math.round(scored.reduce((sum, category) => sum + category.score, 0) / scored.length), categoryScores: scored.map(({ label, score }) => ({ label, score })), attribution: { landing_page: typeof window !== "undefined" ? window.location.href : "/audit", referrer: typeof document !== "undefined" ? document.referrer : "" } }); } catch { setSubmitError("Your result is ready. We could not save a copy to the dashboard, but nothing is blocking your review."); } }
  return <PageFrame><section className="page-hero"><div className="container py-16 lg:py-24"><Eyebrow>Free client acquisition audit</Eyebrow><h1 className="display-heading mt-6 max-w-3xl text-[#0b1f3a]">Is your coaching business losing potential clients before they <span className="text-[#1261d6]">book a call?</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5b7491]">Answer six focused steps to get an educational diagnostic of the path from attention to sales conversation — and a clear next action.</p></div></section><section className="section-padding bg-white"><div className="container">{!result ? <AuditFormView form={form} step={step} canContinue={canContinue} update={update} setStep={setStep} finish={finish} isPending={submitAudit.isPending} /> : <AuditResult categories={categories} overall={overall} name={form.name} submitError={submitError} />}</div></section></PageFrame>;
}

function AuditFormView({ form, step, canContinue, update, setStep, finish, isPending }: { form: AuditForm; step: number; canContinue: boolean; update: (key: keyof AuditForm, value: string | boolean) => void; setStep: React.Dispatch<React.SetStateAction<number>>; finish: (event?: FormEvent) => void; isPending: boolean }) {
  const headings = ["Let’s start with the basics.", "Tell us about the offer.", "What happens in the flow today?", "Where does attention come from?", "How do prospects currently become clients?", "Where would more support help?"];
  return <div className="mx-auto max-w-3xl"><div className="mb-8 flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-[#163453]">Step {step + 1} of {steps.length}</p><div className="mt-3 flex gap-2">{steps.map((label, index) => <div key={label} className={`h-1.5 w-8 rounded-full sm:w-14 ${index <= step ? "bg-[#1261d6]" : "bg-[#e4edf7]"}`} title={label} />)}</div></div><span className="text-xs font-semibold text-[#91a5bd]">About 3 minutes</span></div><form className="audit-form" onSubmit={finish}><div className="mb-8 border-b border-[#e7eff8] pb-7"><h2 className="text-2xl font-bold text-[#0b1f3a]">{headings[step]}</h2><p className="mt-2 text-sm leading-6 text-[#7890aa]">{step === 0 ? "We use this to tailor the result and send it to you." : step === 1 ? "A little context helps separate a real opportunity from a generic suggestion." : step === 2 ? "Approximate numbers are fine — this is a diagnostic, not an exam." : step === 3 ? "Understanding the first touch helps us spot where the handoff needs clarity." : step === 4 ? "Choose the closest description of the current client journey." : "Choose the closest match. You can add more detail if you want."}</p></div>
    {step === 0 && <div className="grid gap-5 sm:grid-cols-2"><Field label="Your name" value={form.name} onChange={(value) => update("name", value)} placeholder="Jane Smith" required /><Field label="Email address" type="email" value={form.email} onChange={(value) => update("email", value)} placeholder="jane@yourbusiness.com" required /><Field label="Phone number" value={form.phone} onChange={(value) => update("phone", value)} placeholder="+1 555 000 0000" required /><Field label="Website or profile link" value={form.website} onChange={(value) => update("website", value)} placeholder="https://" /><Field label="Instagram" value={form.instagram} onChange={(value) => update("instagram", value)} placeholder="@yourhandle" /><SelectField label="Primary niche" value={form.niche} onChange={(value) => update("niche", value)} options={["Health & fitness coaching", "Nutrition coaching", "Business coaching", "Career coaching", "Wellness coaching", "Other"]} placeholder="Choose a niche" /></div>}
    {step === 1 && <div className="grid gap-5"><Field label="What do you sell?" value={form.offer} onChange={(value) => update("offer", value)} placeholder="e.g. 12-week 1:1 coaching" required /><div className="grid gap-5 sm:grid-cols-2"><SelectField label="Typical offer price" value={form.price} onChange={(value) => update("price", value)} options={["Under $500", "$500–$1,500", "$1,500–$3,000", "$3,000+"]} placeholder="Choose a range" required /><Field label="Who is it for?" value={form.niche} onChange={(value) => update("niche", value)} placeholder="e.g. busy professionals" required /></div></div>}
    {step === 2 && <div className="grid gap-5 sm:grid-cols-3"><SelectField label="Monthly leads" value={form.monthlyLeads} onChange={(value) => update("monthlyLeads", value)} options={["0", "1–10", "11–25", "26–50", "51–100", "100+"]} placeholder="Choose" required /><SelectField label="Monthly inquiries" value={form.monthlyInquiries} onChange={(value) => update("monthlyInquiries", value)} options={["0", "1–5", "6–10", "11–25", "25+"]} placeholder="Choose" required /><SelectField label="Monthly booked calls" value={form.bookedCalls} onChange={(value) => update("bookedCalls", value)} options={["0", "1–5", "6–10", "11–20", "20+"]} placeholder="Choose" required /></div>}
    {step === 3 && <ChoiceGrid value={form.leadSource} update={(value) => update("leadSource", value)} options={["website", "instagram", "facebook", "youtube", "tiktok", "ads", "referrals", "other"].map((value) => ({ value, label: value[0].toUpperCase() + value.slice(1) }))} />}
    {step === 4 && <ChoiceGrid value={form.currentSystem} update={(value) => update("currentSystem", value)} options={[{ value: "dm", label: "DM" }, { value: "website", label: "Website" }, { value: "landing-page", label: "Landing Page" }, { value: "application", label: "Application" }, { value: "booking-page", label: "Booking Page" }, { value: "referral", label: "Referral" }, { value: "other", label: "Other" }]} />}
    {step === 5 && <><ChoiceGrid value={form.challenge} update={(value) => update("challenge", value)} options={[{ value: "not-enough-leads", label: "Not enough leads" }, { value: "low-quality-leads", label: "Low-quality leads" }, { value: "leads-no-response", label: "Leads don’t respond" }, { value: "people-dont-book", label: "People don’t book" }, { value: "no-shows", label: "No-shows" }, { value: "poor-follow-up", label: "Poor follow-up" }, { value: "low-conversion", label: "Low sales conversion" }, { value: "other", label: "Other" }]} /><div className="mt-6 space-y-3 rounded-2xl bg-[#f8fbff] p-4"><Consent checked={form.marketingConsent} onChange={(value) => update("marketingConsent", value)}>I agree to receive my audit result and relevant email follow-up from CoachFlow.</Consent><Consent checked={form.smsConsent} onChange={(value) => update("smsConsent", value)}>I consent to SMS reminders about a requested strategy call. (Optional)</Consent><Consent checked={form.whatsappConsent} onChange={(value) => update("whatsappConsent", value)}>I consent to WhatsApp reminders about a requested strategy call. (Optional)</Consent></div></>}
    <div className="mt-9 flex flex-col-reverse justify-between gap-3 border-t border-[#e7eff8] pt-6 sm:flex-row">{step > 0 ? <button type="button" className="button button-secondary" onClick={() => setStep((current) => current - 1)}><ArrowLeft size={16} /> Back</button> : <span />}{step < steps.length - 1 ? <button type="button" className="button button-primary" disabled={!canContinue} onClick={() => setStep((current) => current + 1)}>Continue <ArrowRight size={16} /></button> : <button type="submit" className="button button-primary" disabled={!canContinue || isPending}>{isPending ? "Building your audit…" : <>See my audit <ArrowRight size={16} /></>}</button>}</div><div className="mt-6 flex items-center justify-center gap-2 text-xs font-semibold text-[#91a5bd]"><LockKeyhole size={14} /> Your information is only used to prepare your requested result.</div></form></div>;
}

function AuditResult({ categories, overall, name, submitError }: { categories: Category[]; overall: number; name: string; submitError: string }) { const lowest = [...categories].sort((a, b) => a.score - b.score)[0]; const label = overall <= 40 ? "Major opportunity" : overall <= 60 ? "Developing system" : overall <= 80 ? "Strong foundation" : "Advanced system"; return <div className="mx-auto max-w-5xl"><div className="result-header"><div><Eyebrow>Personalized diagnostic</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-[-0.04em] text-[#0b1f3a]">Your overall client acquisition health<span className="text-[#1261d6]">.</span></h2><p className="mt-2 text-sm text-[#7188a3]">Prepared for {name || "your coaching business"}</p></div><div className="result-score"><span>{overall}</span><small>/100</small></div></div><div className="mt-7 inline-flex rounded-full bg-[#eaf3ff] px-4 py-2 text-sm font-bold text-[#1261d6]">{label}</div><div className="mt-8 rounded-3xl bg-[#0b1f3a] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.17em] text-[#83b8ff]">Your biggest opportunity</p><h3 className="mt-3 text-2xl font-bold">{lowest?.label || "Follow-Up"}</h3><p className="mt-3 max-w-2xl text-sm leading-7 text-[#c8dbef]">{lowest?.opportunity || "Clarify the next step between interest and a qualified conversation."}</p><div className="mt-5 grid gap-3 text-sm font-semibold text-[#d6e5f4] md:grid-cols-3"><span>01. Clarify one next step</span><span>02. Add useful follow-up</span><span>03. Connect booking to fit</span></div></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{categories.map((category) => <div key={category.label} className="result-card"><div className="flex items-center justify-between"><span className="text-sm font-bold text-[#365372]">{category.label}</span><span className="text-xl font-black text-[#1261d6]">{category.score}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#e6eff9]"><div className="h-full rounded-full bg-[#1261d6]" style={{ width: `${category.score}%` }} /></div><p className="mt-5 text-sm leading-6 text-[#7188a3]">{category.explanation}</p></div>)}</div>{submitError && <p className="mt-6 rounded-xl bg-[#fff7e8] px-4 py-3 text-sm font-semibold text-[#956a15]">{submitError}</p>}<div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/book" className="button button-primary">Talk through my results <ArrowRight size={17} /></Link><Link href="/contact" className="button button-secondary">Ask a question <ArrowRight size={17} /></Link></div><p className="mt-6 text-xs leading-6 text-[#91a5bd]">This score is an educational diagnostic based only on the information provided. It is not a guarantee or prediction of business performance, lead volume, revenue, or client results.</p></div>; }
function ChoiceGrid({ value, update, options }: { value: string; update: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <div className="grid gap-3 sm:grid-cols-2">{options.map((option) => <label key={option.value} className={`choice-card ${value === option.value ? "is-selected" : ""}`}><input type="radio" name="choice" value={option.value} checked={value === option.value} onChange={() => update(option.value)} /><span className="choice-radio" /><span className="text-sm font-semibold text-[#365372]">{option.label}</span></label>)}</div>; }
function Field({ label, value, onChange, placeholder, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <label className="form-label">{label}<input className="input-field" type={type} value={value} placeholder={placeholder} required={required} onChange={(event) => onChange(event.target.value)} /></label>; }
function SelectField({ label, value, onChange, options, placeholder, required = false }: { label: string; value: string; onChange: (value: string) => void; options: string[]; placeholder: string; required?: boolean }) { return <label className="form-label">{label}<select className="input-field" value={value} required={required} onChange={(event) => onChange(event.target.value)}><option value="">{placeholder}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
function Consent({ checked, onChange, children }: { checked: boolean; onChange: (value: boolean) => void; children: React.ReactNode }) { return <label className="flex cursor-pointer items-start gap-3 text-xs leading-5 text-[#6b829d]"><input className="mt-1 h-4 w-4 accent-[#1261d6]" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />{children}</label>; }
