import type { ReactNode } from "react";
import { ArrowRight, Calendar, Check, CheckCircle2, Mail, MapPin, ShieldCheck, Sparkles, Target, Timer, Wrench } from "lucide-react";
import { Link } from "wouter";
import { Eyebrow, PageFrame, PrimaryButton, SecondaryButton, SectionIntro } from "@/components/SiteShell";

const process = [
  { no: "01", title: "Diagnose", body: "Start with the offer, audience, traffic sources, and the moments where prospects tend to stall. No assumptions — just a useful baseline.", icon: Target },
  { no: "02", title: "Design", body: "Map the simplest path from attention to qualified conversation, including what to say, what to ask, and when to follow up.", icon: Sparkles },
  { no: "03", title: "Build", body: "Bring the pages, forms, nurture, booking, and tracking into one connected experience your prospects can actually move through.", icon: Wrench },
  { no: "04", title: "Optimize", body: "Use real signals — not vanity metrics — to improve the places where good-fit conversations are won or lost.", icon: ShieldCheck },
];

export function HowItWorks() {
  return <PageFrame><PageHero eyebrow="How it works" title={<>A client acquisition system should feel like a <span className="text-[#1261d6]">path, not a puzzle.</span></>} body="We work from the prospect’s point of view — connecting the parts of your acquisition journey so each step makes the next one easier." /><section className="section-padding bg-white"><div className="container grid gap-5 md:grid-cols-2">{process.map((item) => { const Icon = item.icon; return <div key={item.no} className="process-card"><div className="flex items-start justify-between"><span className="text-sm font-bold text-[#a4b7cc]">{item.no}</span><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eaf3ff] text-[#1261d6]"><Icon size={21} /></div></div><h3 className="mt-9 text-2xl font-bold text-[#0b1f3a]">{item.title}</h3><p className="mt-4 text-base leading-8 text-[#687f9b]">{item.body}</p></div> })}</div></section><section className="section-padding bg-[#f4f8fd]"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><SectionIntro eyebrow="A practical partnership" title={<>Clarity first. <span className="text-[#1261d6]">Complexity only when it earns its place.</span></>} body="We are not here to add more tools to your stack. We are here to make the path from interest to conversation more intentional." /><div className="rounded-3xl border border-[#dce9f7] bg-white p-7 shadow-[0_20px_55px_rgba(18,97,214,0.08)]"><div className="flex items-center gap-3 border-b border-[#e7eff8] pb-5"><Timer className="text-[#1261d6]" size={21} /><span className="font-bold text-[#163453]">The first conversation covers</span></div><ul className="mt-6 space-y-4">{["Your current offer and audience", "Where inquiries come from today", "The handoffs between interest and booking", "What a useful next step could look like"].map((item) => <li key={item} className="flex items-center gap-3 text-sm font-semibold text-[#536d8b]"><CheckCircle2 size={17} className="shrink-0 text-[#1261d6]" />{item}</li>)}</ul><div className="mt-7"><PrimaryButton href="/book">Book a strategy call</PrimaryButton></div></div></div></section></PageFrame>;
}

export function SystemPage() {
  const stages = ["Attract", "Capture", "Nurture", "Qualify", "Book", "Follow up", "Convert"];
  return <PageFrame><PageHero eyebrow="The client acquisition system" title={<>Every handoff is part of the <span className="text-[#1261d6]">experience.</span></>} body="CoachFlow brings your strategy, funnel, automation, booking, and conversion decisions into one operating view." /><section className="section-padding bg-white"><div className="container"><div className="system-map">{stages.map((stage, index) => <div key={stage} className="system-row"><div className="system-index">0{index + 1}</div><div className="system-stage"><span className="system-stage-dot" /><h3>{stage}</h3></div><p>{["Content, outreach, and ads create the first invitation.", "A page, lead magnet, or application makes interest identifiable.", "Email, SMS, and follow-up keep the conversation useful.", "The right questions help you recognize fit and readiness.", "A clear calendar turns intent into a scheduled conversation.", "Reminders and re-engagement respect the prospect’s timing.", "A better-informed call creates a better sales conversation."][index]}</p></div>)}</div></div></section><section className="section-padding bg-[#0b1f3a]"><div className="container grid gap-10 lg:grid-cols-2"><div><Eyebrow dark>What this is not</Eyebrow><h2 className="display-heading mt-5 text-white">Not another disconnected stack of <span className="text-[#83b8ff]">tools.</span></h2></div><div className="space-y-4 text-lg leading-8 text-[#c4d7ed]"><p>We do not start with “Which platform should we use?” We start with “What should your prospect experience next?”</p><p>Then we choose the lightest, clearest combination of pages, automation, and tracking to support that journey.</p><Link href="/audit" className="inline-flex items-center gap-2 pt-3 text-base font-bold text-[#83b8ff]">Find your next best step <ArrowRight size={17} /></Link></div></div></section></PageFrame>;
}

export function AboutPage() { return <PageFrame><PageHero eyebrow="About CoachFlow" title={<>Build the system behind the <span className="text-[#1261d6]">conversation.</span></>} body="CoachFlow exists for coaches who have expertise, an offer, and some attention — but want a clearer, more dependable way to turn interest into qualified sales conversations." /><section className="section-padding bg-white"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="about-card"><div className="about-card-grid" /><span className="text-7xl font-black tracking-[-0.08em] text-white">A<span className="text-[#83b8ff]">/</span></span><p className="mt-10 text-sm font-semibold leading-7 text-[#d3e3f3]">Clarity is a competitive advantage when every conversation counts.</p></div><div className="max-w-xl"><Eyebrow>Our point of view</Eyebrow><h2 className="display-heading mt-5">Good acquisition is not about adding <span className="text-[#1261d6]">more noise.</span></h2><div className="mt-7 space-y-5 text-base leading-8 text-[#647c98]"><p>It is about making the next step easier to understand — for you and for the person considering your coaching.</p><p>That means taking the whole path seriously: the message that earns attention, the page that creates clarity, the follow-up that respects timing, and the conversation that helps both sides make a better decision.</p><p>Our work sits at the intersection of funnel strategy, thoughtful automation, and practical conversion design.</p></div><div className="mt-8"><PrimaryButton href="/contact">Start a conversation</PrimaryButton></div></div></div></section></PageFrame>; }

export function InsightsPage() { const posts = [{ type: "Perspective", title: "Your audience is not a funnel — but it needs somewhere to go.", read: "5 min read" }, { type: "Framework", title: "The seven handoffs between attention and a booked call.", read: "7 min read" }, { type: "Field note", title: "What to look for before you add another automation.", read: "4 min read" }]; return <PageFrame><PageHero eyebrow="Insights" title={<>Ideas for building a more <span className="text-[#1261d6]">intentional path.</span></>} body="Practical thinking on client acquisition systems, follow-up, qualification, and the small decisions that create better conversations." /><section className="section-padding bg-white"><div className="container grid gap-5 md:grid-cols-3">{posts.map((post, i) => <article key={post.title} className={`insight-card ${i === 0 ? "insight-featured" : ""}`}><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[0.17em] text-[#1261d6]">{post.type}</span><span className="text-xs font-semibold text-[#9ab0c8]">{post.read}</span></div><div className="insight-art"><span>{String(i + 1).padStart(2, "0")}</span></div><h3 className="mt-6 text-xl font-bold leading-8 text-[#163453]">{post.title}</h3><Link href="/contact" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#1261d6]">Read the note <ArrowRight size={15} /></Link></article>)}</div></section><section className="section-padding bg-[#f4f8fd]"><div className="container"><div className="newsletter-panel"><div><Eyebrow>Occasional, useful notes</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-[-0.04em] text-[#0b1f3a]">Make the next move with more clarity.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><input className="input-field min-w-0 sm:w-64" placeholder="Your email address" aria-label="Your email address" /><button className="button button-primary">Keep me posted <ArrowRight size={16} /></button></div></div></div></section></PageFrame>; }

export function ContactPage() { return <PageFrame><PageHero eyebrow="Contact CoachFlow" title={<>Have a question about your <span className="text-[#1261d6]">next step?</span></>} body="Tell us a little about what you are building. We will point you toward the most useful place to start." /><section className="section-padding bg-white"><div className="container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><div className="space-y-5"><div className="contact-item"><Mail size={20} /><div><p className="font-bold text-[#163453]">Email</p><p className="mt-1 text-sm text-[#6f86a2]">hello@coachflow.co</p></div></div><div className="contact-item"><Calendar size={20} /><div><p className="font-bold text-[#163453]">Prefer a focused conversation?</p><Link href="/book" className="mt-1 inline-flex text-sm font-bold text-[#1261d6]">Book a strategy call <ArrowRight size={15} className="ml-2" /></Link></div></div><div className="contact-item"><MapPin size={20} /><div><p className="font-bold text-[#163453]">Working with coaches across</p><p className="mt-1 text-sm text-[#6f86a2]">The United States and beyond</p></div></div></div></div><ContactForm /></div></section></PageFrame>; }

function ContactForm() { return <form className="rounded-3xl border border-[#dce9f7] bg-[#f8fbff] p-6 sm:p-8" onSubmit={(event) => event.preventDefault()}><div className="grid gap-5 sm:grid-cols-2"><label className="form-label">Your name<input className="input-field" required placeholder="Jane Smith" /></label><label className="form-label">Email address<input type="email" className="input-field" required placeholder="jane@yourcoachingbusiness.com" /></label></div><label className="form-label mt-5">What are you working on?<textarea className="input-field min-h-36 resize-y" placeholder="A little context helps us make the reply useful." /></label><button className="button button-primary mt-6" type="submit">Send message <ArrowRight size={17} /></button></form>; }

export function BookPage() { return <PageFrame><PageHero eyebrow="Book a strategy call" title={<>Let’s build your <span className="text-[#1261d6]">client acquisition system.</span></>} body="A focused conversation to review your current offer, lead generation, funnel, follow-up, booking process, and conversion opportunities." /><section className="section-padding bg-white"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div className="rounded-3xl bg-[#0b1f3a] p-7 text-white"><Eyebrow dark>What we will review</Eyebrow><ul className="mt-7 space-y-4">{["Current coaching offer", "Lead generation and audience", "Funnel and follow-up", "Booking and qualification", "Conversion opportunities"].map((item) => <li key={item} className="flex items-center gap-3 text-sm font-semibold text-[#d3e3f3]"><Check size={16} className="text-[#83b8ff]" />{item}</li>)}</ul><p className="mt-9 border-t border-white/10 pt-5 text-xs leading-6 text-[#9eb8d5]">Calendar availability will appear here once your preferred scheduling provider is connected. No fake slots, no guesswork.</p></div><div className="booking-placeholder"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#eaf3ff] text-[#1261d6]"><Calendar size={25} /></div><h2 className="mt-6 text-2xl font-bold text-[#0b1f3a]">Connect your calendar to continue</h2><p className="mt-3 max-w-md text-base leading-7 text-[#6a819d]">This page is ready for a configurable calendar integration such as Calendly or another provider. Once connected, your live availability and confirmation flow can plug in here.</p><a href="mailto:hello@coachflow.co?subject=Connect%20my%20calendar" className="button button-primary mt-7">Request calendar setup <ArrowRight size={17} /></a><span className="mt-5 text-xs font-semibold text-[#91a5bd]">Integration placeholder — availability is never hard-coded.</span></div></div></section></PageFrame>; }

export function PrivacyPage() { return <LegalPage title="Privacy policy" updated="September 2026"><p>CoachFlow respects your privacy. This page is a clear starting point for the policy that will govern how information submitted through this website is handled.</p><h2>Information you submit</h2><p>When you request an audit, contact the team, or request a strategy call, we may collect the information you choose to provide, such as your name, email address, website, coaching context, and business goals.</p><h2>How information is used</h2><p>Information is used to provide the requested diagnostic, respond to inquiries, improve the site experience, and prepare for a relevant conversation. We do not promise that a score or diagnostic predicts business performance.</p><h2>Questions</h2><p>For privacy questions, contact <a href="mailto:hello@coachflow.co">hello@coachflow.co</a>.</p></LegalPage>; }
export function TermsPage() { return <LegalPage title="Terms of service" updated="September 2026"><p>By using this website, you agree to use it lawfully and to provide accurate information when requesting an audit or conversation.</p><h2>Educational information</h2><p>CoachFlow’s diagnostic, content, and conversations are educational and strategic in nature. They are not guarantees of leads, revenue, clients, or business performance.</p><h2>Third-party services</h2><p>Future booking, email, messaging, and analytics integrations may be provided by third parties and may be governed by their own terms and privacy policies.</p><h2>Questions</h2><p>For questions about these terms, contact <a href="mailto:hello@coachflow.co">hello@coachflow.co</a>.</p></LegalPage>; }

function PageHero({ eyebrow, title, body }: { eyebrow: string; title: ReactNode; body: string }) { return <section className="page-hero"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="container relative py-20 lg:py-28"><Eyebrow>{eyebrow}</Eyebrow><h1 className="display-heading mt-6 max-w-4xl text-[#0b1f3a]">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5b7491]">{body}</p></div></section>; }
function LegalPage({ title, updated, children }: { title: string; updated: string; children: ReactNode }) { return <PageFrame><section className="page-hero"><div className="container py-20"><Eyebrow>CoachFlow / Fine print</Eyebrow><h1 className="display-heading mt-6 text-[#0b1f3a]">{title}</h1><p className="mt-5 text-sm font-semibold text-[#8ca1b9]">Last updated {updated}</p></div></section><article className="legal-content container">{children}</article></PageFrame>; }
